name: Build and Push Base Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
    paths:
      - 'Dockerfile'  # Only trigger if the Dockerfile is changed
      - '.github/workflows/*.yml'  # Also trigger if this workflow file changes

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/stalderstudios/mapify-api-baseimage:latest
          ghcr.io/stalderstudios/mapify-api-baseimage:${{github.sha}}